#!/usr/bin/env bash

lock() {
    #  killall compton
    h
    #  compton -b
}

case "$1" in
    lock)
       	i3lock-fancy -gp -- scrot -z 
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        systemctl suspend
        ;;
    hibernate)
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 [lock|logout|suspend|hibernate|reboot|shutdown]"
        exit 2
esac

exit 0

