#!/usr/bin/env bash

lock() {
    dbus-send --type=method_call --dest=org.gnome.ScreenSaver /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock
    
    # suspend message display
    pkill -u "$USER" -USR1 dunst
    # lock the screen
    i3lock-fancy-rapid 10 pixel
    # resume message display
    wait && pkill -u "$USER" -USR2 dunst;
}

susp() {
    # suspend message display
    pkill -u "$USER" -USR1 dunst;
    # lock the screen
    i3lock-fancy-rapid 10 pixel && dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Suspend" boolean:true 
    # resume message display
    wait $pid pkill -u "$USER" -USR2 dunst;
}

hibernate() {
    # suspend message display
    pkill -u "$USER" -USR1 dunst;
    # lock the screen
    i3lock-fancy-rapid 10 pixel
    pid=$!
    systemctl hibernate
    # resume message display
    wait $pid && pkill -u "$USER" -USR2 dunst;
}

windowsreboot() {
    # suspend message display
    pkill -u "$USER" -USR1 dunst;
    # lock the screen
    i3lock-fancy-rapid 10 pixel
    pid=$!
    systemctl hybrid-sleep
    # resume message display
    wait $pid && pkill -u "$USER" -USR2 dunst;
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        susp
        ;;
    hibernate)
        hibernate
        ;;
    windowsreboot)
        windowsreboot
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 [lock|logout|suspend|hibernate|windowsreboot|reboot|shutdown]"
        exit 2
esac

exit0

