#!/bin/sh
#!/bin/bash

workspace1="1 "
workspace2="2 "
workspace3="3 "
workspace4="4 "
workspace5="5 "
workspace6="6 "
workspace7="7 "
workspace8="8 "

xrandr --fb 1920x1080 --output eDP-1 --mode 1920x1080 --scale-from 1920x1080 --output HDMI-1 --mode 1920x1080 --scale 1x1 --same-as eDP-1


i3-msg "workspace $workspace1, move workspace to output primary"
i3-msg "workspace $workspace2, move workspace to output primary"
i3-msg "workspace $workspace3, move workspace to output primary"
i3-msg "workspace $workspace4, move workspace to output primary"
i3-msg "workspace $workspace5, move workspace to output primary"
i3-msg "workspace $workspace6, move workspace to output primary" 
i3-msg "workspace $workspace7, move workspace to output primary"
i3-msg "workspace $workspace8, move workspace to output primary"

nitrogen --restore
