#!/bin/bash

mons -e right

# Left laptop
# xrandr --output HDMI-2 --off --output DP-1 --primary --mode 1920x1080 --pos 1440x0 --rotate normal --output HDMI-1 --off --output eDP-1 --mode 1920x1080 --pos 0x270 --rotate normal --scale 0.75x0.75 --output DP-2 --off
xrandr --output HDMI-2 --off --output DP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1 --off --output eDP-1 --mode 1920x1080 --pos 1920x270 --rotate normal --scale 0.75x0.75 --output DP-2 --off

workspace1="1 "
workspace2="2 "
workspace3="3 "
workspace4="4 "
workspace5="5 "
workspace6="6 "
workspace7="7 "
workspace8="8 "

PRIMARY=$( xrandr -q | awk '/ connected primary/ {print $1}' )
SECONDARY="eDP-1"

i3-msg "workspace $workspace3, move workspace to output PRIMARY" 
i3-msg "workspace $workspace1, move workspace to output PRIMARY"  
i3-msg "workspace $workspace2, move workspace to output PRIMARY"
#i3-msg "workspace $workspace4, move workspace to output PRIMARY"
#i3-msg "workspace $workspace5, move workspace to output SECONDARY"
#i3-msg "workspace $workspace6, move workspace to output SECONDARY"
i3-msg "workspace $workspace8, move workspace to output SECONDARY"
i3-msg "workspace $workspace7, move workspace to output SECONDARY"

nitrogen --restore 
